src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only add a Project with the status &quot;Proposed&quot; or &quot;Ongoing&quot;</errorMessage>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>Proposed, Ongoing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Test_Case__c</fullName>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Case Steps</relationshipLabel>
        <relationshipName>Test_Case_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Case Step</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Test Case Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Case Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testCaseStepsControllerTest.cls
@isTest
private class testCaseStepsControllerTest {
    @isTest
    static void getStepsTest(){
        
        Test.startTest();
        Project__c p = new Project__c();
        Test_Case__c tCase = new Test_Case__c();
        Test_Case_Step__c step = new Test_Case_Step__c();
        dataFactory.createProject(p);
        dataFactory.createTestCase(p, tCase);
        dataFactory.createTestCaseStep(step, tCase);
        
        testCaseStepsController.getSteps(tCase.Id);
        Test.stopTest();
        
    }
    
    @isTest
    static void updateStepsListTest(){
        Test.startTest();
        List<Test_Case_Step__c> stepList = new List<Test_Case_Step__c>();
        Project__c p = new Project__c();
        Test_Case__c tCase = new Test_Case__c();
        Test_Case_Step__c step = new Test_Case_Step__c();
        dataFactory.createProject(p);
        dataFactory.createTestCase(p, tCase);
        dataFactory.createTestCaseStep(step, tCase);
        stepList.add(step);
        testCaseStepsController.updateStepsList(stepList);
        Test.stopTest();
        
    }
}