src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ongoingProjectsBatch.cls
global class ongoingProjectsBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Status__c, Cases_Amount__c, OwnerId FROM Project__c ' + 
            'WHERE Status__c = \'Ongoing\''
        );
    }
    global void execute(Database.BatchableContext bc, List<Project__c> scope){
        List<Id> ownerIds = new List<Id>();
        
        for(Project__c p : scope){
            if(!ownerIds.contains(p.OwnerId)){
                ownerIds.add(p.OwnerId);
            }
        }
        
        for(id owner : ownerIds){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(owner); 
            mail.setSenderDisplayName('Salesforce Support'); 
            mail.setUseSignature(false); 
            mail.setBccSender(false); 
            mail.setSaveAsActivity(false); 
            EmailTemplate et=[Select id, Name from EmailTemplate where Name=:'ongoingProjects']; 
            mail.setTemplateId(et.id); 
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            
        }
        
    }    
    global void finish(Database.BatchableContext bc){
        
    }    
    
}