src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only add a Project with the status &quot;Proposed&quot; or &quot;Ongoing&quot;</errorMessage>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>Proposed, Ongoing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ongoingProjectsBatchTest.cls
@isTest
private  class ongoingProjectsBatchTest {
    @isTest
    static void myTest(){
        
        Test.startTest();
        Project__c p = new Project__c();
        Test_Case__c tCase = new Test_Case__c();
        
        dataFactory.createProject(p);
        dataFactory.createTestCase(p, tCase);
        
        ongoingProjectsBatch b = new ongoingProjectsBatch();
        Database.executeBatch(b);
        Test.stopTest();
    }
}