src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preconditions__c</fullName>
        <label>Preconditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only add a Project with the status &quot;Proposed&quot; or &quot;Ongoing&quot;</errorMessage>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>Proposed, Ongoing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/projectTileController.cls
public class projectTileController {
    @AuraEnabled
    public static List<Project__c> getProjects (){
        String[] fieldsToCheck = new String[] {
            'Id', 'Name', 'Status__c'
                };
                    
                    Map<String,Schema.SObjectField> fieldDescribeTokens = 
                    Schema.SObjectType.Project__c.fields.getMap();
        
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        
        return[SELECT Id, Name, Status__c, Description__c
               FROM Project__c 
               WHERE Status__c = 'Ongoing'];
    }
    
    
    @AuraEnabled
    public static List<Test_Case__c> getCases(Project__c project)
    {
        return[SELECT Id,Name, Title__c, LastModifiedDate,Project__c , Description__c, Preconditions__c, User_Story__c 
               FROM Test_Case__c WHERE Project__c =: project.Id
               ORDER BY LastModifiedDate DESC];   
    }
    
    @AuraEnabled
    public static List<Test_Case__c> deleteTestCase(Test_Case__c testCase) {
        
        delete testCase;
        return [SELECT Id,Name, Title__c, LastModifiedDate,Project__c 
                FROM Test_Case__c WHERE Project__c =: testCase.Project__c 
                ORDER BY LastModifiedDate DESC];
    }
    @AuraEnabled
    public static List<Test_Case__c> createTestCase(Test_Case__c newTestCase, Project__c project){
       
        upsert newTestCase;
        return [SELECT Id,Name, Title__c, LastModifiedDate,Project__c , Description__c, Preconditions__c, User_Story__c 
                FROM Test_Case__c WHERE Project__c =: project.Id 
                ORDER BY LastModifiedDate DESC];
        
    }
}