src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preconditions__c</fullName>
        <label>Preconditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only add a Project with the status &quot;Proposed&quot; or &quot;Ongoing&quot;</errorMessage>
            <filterItems>
                <field>Project__c.Status__c</field>
                <operation>equals</operation>
                <value>Proposed, Ongoing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/projectTileControllerTest.cls
@isTest
public class projectTileControllerTest {
    @isTest
    static void getProjectsTest(){
        Test.startTest();
        Project__c p = new Project__c();
        dataFactory.createProject(p);
        projectTileController.getProjects();
        Test.stopTest();
    }
    @isTest
    static void getCasesTest(){
        Test.startTest();
        Project__c p = new Project__c();
        dataFactory.createProject(p);
        Test_Case__c tCase = new Test_Case__c();
        dataFactory.createTestCase(p, tCase);
        projectTileController.getCases(p);
        Test.stopTest();
    }
    @isTest
    static void deleteTestCaseTest(){
        Test.startTest();
        Project__c p = new Project__c();
        dataFactory.createProject(p);
        Test_Case__c tCase = new Test_Case__c();
        dataFactory.createTestCase(p, tCase);
        projectTileController.deleteTestCase(tCase);
        Test.stopTest();
    }
    @isTest
    static void createTestCaseTest(){
        Test.startTest();
        Project__c p = new Project__c();
        dataFactory.createProject(p);
        Test_Case__c tCase = new Test_Case__c();
        tCase.Project__c = p.Id;
        tCase.Title__c = 'test Title';
        tCase.Description__c = 'test description';
        tCase.Preconditions__c = 'test preconditions';
        tCase.User_Story__c = 'test.com';
        projectTileController.createTestCase(tCase, p);
        Test.stopTest();
    }
}