src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Step_Position__c</fullName>
        <label>Step Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Case Steps</relationshipLabel>
        <relationshipName>Test_Case_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Case Step</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Test Case Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Case Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testCaseStepsController.cls
public class testCaseStepsController {
    @AuraEnabled
    public static List<Test_Case_Step__c> getSteps(Id recordCase)
    {
        return[SELECT Id,Name, Test_Case__c, Step_Position__c, Description__c, Expected_Result__c FROM Test_Case_Step__c 
               WHERE Test_Case__c =: recordCase ORDER BY Step_Position__c ASC];
    }
    @AuraEnabled
    public static List<Test_Case_Step__c> updateStepsList(List<Test_Case_Step__c> spliceList)
    {	
        for(integer i = 0; i < spliceList.size(); i++){
            
            spliceList[i].Step_Position__c = i + 1;   
        }
        
        update spliceList;
        
        return spliceList;
    }
}